[opener]
edit = [
	{ run = "nvim %s", desc = "nvim", block = true, for = "unix" },
	{ run = "nvim %s", desc = "nvim", block = true, for = "windows" },
]
explorer = [
	{ run = 'start "" %s1', desc = "Default", orphan = true, for = "windows" },
	{ run = "xdg-open %s1", desc = "Default", orphan = true, for = "linux" },
	{ run = 'explorer %s1', desc = "Windows Explorer", orphan = true, for = "windows" },
	{ run = '"C:\\Program Files\\GPSoftware\\Directory Opus\\dopus.exe" %s1', desc = "Directory Opus", orphan = true, for = "windows" },
	{ run = '"%LOCALAPPDATA%\\Voidstar\\FilePilot\\FPilot.exe" %s1', desc = "File Pilot", orphan = true, for = "windows" },
]

[open]
prepend_rules = [
	{ url = "*/", use = [ "explorer", "edit" ] },
]
