[window]
opacity = 1
padding.x = 10
padding.y = 10

#decorations = "Full"
#decorations_theme_variant = "Light" # "Dark"

[font]

#family = "JetBrainsMono Nerd Font Mono"
normal.family = "JetBrainsMono Nerd Font Mono"
bold.family = "JetBrainsMono Nerd Font Mono"
italic.family = "JetBrainsMono Nerd Font Mono"
bold_italic.family = "JetBrainsMono Nerd Font Mono"

size = 15


[general]

import = [ "~/.config/alacritty/tokyo-night-storm.toml" ] # or tokyo-night-storm.toml
