# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Enable mouse scrolling
setw -g mouse on

# Set bar colour blue (enable for remote tmux)
# set -g status-bg "#50AFF0"

#========================================================================

# Reload config with <leader>r
bind r source-file $XDG_CONFIG_HOME/tmux/tmux.conf \; display "Config reloaded!"

set-window-option -g mode-keys vi

# vim-like pane switching
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

set -g @tmux_sessionizer "$XDG_CONFIG_HOME/tmux/tmux-sessionizer"

# Run sessionizer script
bind-key -r f run-shell "tmux new-window #{@tmux_sessionizer}"
#---------------------------------------------------------------------------
bind-key -r H run-shell "#{@tmux_sessionizer} ~"
bind-key -r C run-shell "#{@tmux_sessionizer} ~/.dotfiles/"
bind-key -r N run-shell "#{@tmux_sessionizer} ~/.config/nvim/"
bind-key -r J run-shell "#{@tmux_sessionizer} ~/dev/cresh/creshsite/"
